name: flutter_module
description: A new Flutter module project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  micro_core:
    path: ../micro_core/

  micro_app_profile:
    path: ../apps/micro_app_profile/

  micro_app_settings:
    path: ../apps/micro_app_settings/

  micro_app_statements:
    path: ../apps/micro_app_statements/

  dependencies:
    path: ../commons/dependencies/

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: 22.7.4

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/inter_bold.ttf
        - asset: fonts/inter_light.ttf
        - asset: fonts/inter_medium.ttf
        - asset: fonts/inter_regular.ttf
        - asset: fonts/inter_semibold.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.main_app.main_app
    iosBundleIdentifier: com.mainapp.mainApp
